=== Nazaret8/ejercicios-lenguaje-marcas/Ejercicios Nazaret/Batería XML, DTD, XML Schema/EjerciciosBatería/Ejercicio1_6_Schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empleados">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="empleado" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="apellidos" type="xs:string"/>
              <xs:element name="fechaNacimiento" type="xs:date"/>
              <xs:element name="puesto">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titulo" type="xs:string"/>
                    <xs:element name="departamento" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="direccion" type="xs:string" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Nazaret8/ejercicios-lenguaje-marcas/Ejercicios Nazaret/Batería XML, DTD, XML Schema/EjerciciosBatería/Ejercicio1_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Ejercicio1_6_Schema.xsd">
    <empleado id="e001">
        <nombre>Juan</nombre>
        <apellidos>Perez</apellidos>
        <fechaNacimiento>1990-05-15</fechaNacimiento>
        <puesto>
            <titulo>Desarrollador Senior</titulo>
            <departamento>Desarrollo de Software</departamento>
        </puesto>
        <direccion>Avenida Principal, 123</direccion>
    </empleado>
    <empleado id="e002">
        <nombre>Maria</nombre>
        <apellidos>Gomez</apellidos>
        <fechaNacimiento>1985-09-20</fechaNacimiento>
        <puesto>
            <titulo>Gerente de Proyectos</titulo>
            <departamento>Administraci√≥n</departamento>
        </puesto>
    </empleado>
</empleados>
