=== Nazaret8/ejercicios-lenguaje-marcas/Ejercicios Nazaret/Batería XML, DTD, XML Schema/EjerciciosBatería/Ejercicio1_3.dtd
<!ELEMENT factura (cliente, productos, subtotal, iva, total)>
<!ATTLIST factura
    numero CDATA #REQUIRED
    fecha CDATA #REQUIRED>
<!ELEMENT cliente (nombre_cliente, direccion)>
<!ELEMENT nombre_cliente (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre, unidades, precio_unitario)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio_unitario (#PCDATA)>
<!ELEMENT subtotal (#PCDATA)>
<!ELEMENT iva (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== Nazaret8/ejercicios-lenguaje-marcas/Ejercicios Nazaret/Batería XML, DTD, XML Schema/EjerciciosBatería/Ejercicio1_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE factura SYSTEM "Ejercicio1_3.dtd">-->
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio1_3_Schema.xsd" numero="F001" fecha="2024-04-16">
    <cliente>
        <nombre_cliente>Cliente Ejemplo</nombre_cliente>
        <direccion>Calle Ejemplo, 123</direccion>
    </cliente>
    <productos>
        <producto>
            <nombre>Producto A</nombre>
            <unidades>2</unidades>
            <precio_unitario>10.99</precio_unitario>
        </producto>
        <producto>
            <nombre>Producto B</nombre>
            <unidades>1</unidades>
            <precio_unitario>5.49</precio_unitario>
        </producto>
    </productos>
    <subtotal>27.47</subtotal>
    <iva>5.84</iva>
    <total>33.31</total>
</factura>
