=== Nazaret8/ejercicios-lenguaje-marcas/Ejercicios Nazaret/Batería XML, DTD, XML Schema/EjerciciosBatería/Ejercicio1_4.dtd
<!ELEMENT informacion_personal (nombre, apellidos, edad, sexo, direccion, contacto, educacion, habilidades)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (apellido_paterno, apellido_materno)>
<!ELEMENT apellido_paterno (#PCDATA)>
<!ELEMENT apellido_materno (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT direccion (calle, numero_calle, ciudad, codigo_postal, pais)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero_calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT contacto (telefono, correo)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT educacion (titulo, institucion, anio)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT institucion (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT habilidades (habilidad+)>
<!ELEMENT habilidad (#PCDATA)>

=== Nazaret8/ejercicios-lenguaje-marcas/Ejercicios Nazaret/Batería XML, DTD, XML Schema/EjerciciosBatería/Ejercicio1_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE informacion_personal SYSTEM "Ejercicio1_4.dtd">-->
<informacion_personal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio1_4_Schema.xsd" >
    <nombre>Nazaret</nombre>
    <apellidos>
        <apellido_paterno>Andrades</apellido_paterno>
        <apellido_materno>Gonz치lez</apellido_materno>
    </apellidos>
    <edad>19</edad>
    <sexo>femenino</sexo>
    <direccion>
      <calle>C/Luna</calle>
      <numero_calle>2</numero_calle>
      <ciudad>El Cuervo de Sevilla</ciudad>
      <codigo_postal>41749</codigo_postal>
      <pais>Espa침a</pais>
    </direccion>
    <contacto>
      <telefono>658-475-142</telefono>
      <correo>nandgon822@g.educaand.es</correo>
    </contacto>
    <educacion>
      <titulo>Grado Superior Desarrollo de Aplicaciones Multiplataformas</titulo>
      <institucion>IES Laguna de Toll칩n</institucion>
      <anio>2025</anio>
    </educacion>
    <habilidades>
      <habilidad>Lenguajes de programaci칩n: Java, Python, JavaScript</habilidad>
      <habilidad>Desarrollo web: HTML, CSS, React</habilidad>
      <habilidad>Bases de datos: SQL, MongoDB</habilidad>
    </habilidades>
  </informacion_personal>
