=== Nazaret8/ejercicios-lenguaje-marcas/Ejercicios Nazaret/Batería XML, DTD, XML Schema/EjerciciosBatería/Ejercicio1_2.dtd
<!ELEMENT pedido (nombre_cliente, direccion_entrega, productos)>
<!ELEMENT nombre_cliente (#PCDATA)>
<!ELEMENT direccion_entrega (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre, precio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST producto numero_produto CDATA #REQUIRED>

=== Nazaret8/ejercicios-lenguaje-marcas/Ejercicios Nazaret/Batería XML, DTD, XML Schema/EjerciciosBatería/Ejercicio1_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE pedido SYSTEM "Ejercicio1_2.dtd">-->
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio1_2_Schema.xsd">
    <nombre_cliente>Nazaret</nombre_cliente>
    <direccion_entrega>C/Luna Nº2</direccion_entrega>
    <productos>
        <producto numero_produto = "2">
            <nombre>Hamburguesa</nombre>
            <precio>6€</precio>
        </producto>
        <producto numero_produto = "1">
            <nombre>Queso</nombre>
            <precio>0.50€</precio>
        </producto>
        <producto numero_produto = "3">
            <nombre>Cebolla</nombre>
            <precio>0.70€</precio>
        </producto>
    </productos>
</pedido>
